// samples/hello-world/hello-world-react/src/components/CaptureViewer.js
import { CaptureVisionRouter, LicenseManager } from "dynamsoft-capture-vision-router"
import { DDV } from "dynamsoft-document-viewer"
import { useEffect, useState } from "react"
import { initDocDetectModule } from "../utils/initDocDetectModule"
import "dynamsoft-document-viewer/dist/ddv.css"

export default function CaptureViewer(props) {
    const [captureViewer, setCaptureViewer] = useState(null);

    const init = async () => {
        DDV.on("error", (e) => {
            alert(e.message);
        });

        await DDV.setConfig({
            license:
              'DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9',
            engineResourcePath: 'https://cdn.jsdelivr.net/npm/dynamsoft-document-viewer@latest/dist/engine'
        });

        LicenseManager.initLicense(
            'DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9'
        );
        CaptureVisionRouter.engineResourcePath = 'https://cdn.jsdelivr.net/npm/dynamsoft-capture-vision-router@2.0.11/dist/';
        await CaptureVisionRouter.preloadModule(['DDN']);

        const router = await CaptureVisionRouter.createInstance();
        await initDocDetectModule(DDV, router);
      
        const viewer = new DDV.CaptureViewer({
          container: 'viewerContainer',
          viewerConfig: {
            acceptedPolygonConfidence: 60,
            enableAutoCapture: true,
            enableAutoDetect: true
          }
        });

        setCaptureViewer(viewer);
      
        viewer.play({
          resolution: [1920, 1080]
        });
      
        viewer.on('captured', async (e) => {
          const pageData = await viewer.currentDocument.getPageData(e.pageUid);
          props.setImages({
            originalImage: URL.createObjectURL(pageData.raw.data),
            detectedImage: URL.createObjectURL(pageData.display.data)
          });
          props.setShowCaptureViewer(false);
        });
    }

    useEffect(() => {
        init();
    },[]);

    useEffect(() => {
        if(props.showCaptureViewer) {
            captureViewer?.currentDocument.deleteAllPages();
            captureViewer?.play();
        } else {
            captureViewer?.stop();
        }
    },[props.showCaptureViewer]);

    return (
        <div style={props.showCaptureViewer ? {} : { display: 'none' }} id="viewerContainer">

        </div>
    )
}

// samples/hello-world/hello-world-angular/src/app/components/capture-viewer/capture-viewer.component.ts
import { Component, Input, SimpleChanges } from '@angular/core';
import { CaptureVisionRouter, LicenseManager } from 'dynamsoft-capture-vision-router';
import { DDV } from 'dynamsoft-document-viewer';
import type { CaptureViewer, IDocument } from 'dynamsoft-document-viewer';
import { initDocDetectModule } from '../../utils/initDocDetectModule';
import { CapturedImages } from '../../app.component';
import "dynamsoft-document-viewer/dist/ddv.css"

@Component({
  selector: 'app-capture-viewer',
  standalone: true,
  imports: [],
  templateUrl: './capture-viewer.component.html',
  styleUrl: './capture-viewer.component.css'
})

export class CaptureViewerComponent {
  @Input() showCaptureViewer: boolean = true;
  @Input() switchVisibility: (value: boolean) => void = () => {};
  @Input() setImages: (value: CapturedImages) => void = () => {};
  captureViewer: CaptureViewer | null = null;

  async ngOnInit() {
    DDV.on("error", (e: any) => {
      alert(e.message)
    });

    await DDV.setConfig({
      license:
        'DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9',
      engineResourcePath: 'https://cdn.jsdelivr.net/npm/dynamsoft-document-viewer@latest/dist/engine'
    });

    LicenseManager.initLicense(
      'DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9'
    );
    CaptureVisionRouter.engineResourcePath =
      'https://cdn.jsdelivr.net/npm/dynamsoft-capture-vision-router@2.0.11/dist/';
    CaptureVisionRouter.preloadModule(['DDN']);
  
    const router = await CaptureVisionRouter.createInstance();
    await initDocDetectModule(DDV, router);

    this.captureViewer = new DDV.CaptureViewer({
      container: 'viewerContainer',
      viewerConfig: {
        acceptedPolygonConfidence: 60,
        enableAutoCapture: true,
        enableAutoDetect: true
      }
    });

    this.captureViewer.play({
      resolution: [1920, 1080]
    });

    this.captureViewer.on("captured",async (e) => {
      const doc = (this.captureViewer as CaptureViewer).currentDocument as IDocument;
      const pageData = await doc.getPageData(e.pageUid) as any;
      this.switchVisibility(false);
      this.setImages({
        originalImage: URL.createObjectURL(pageData.raw.data),
        detectedImage: URL.createObjectURL(pageData.display.data)
      })
    });
  }

  ngOnChanges(changes: SimpleChanges){
    if(changes['showCaptureViewer']) {
      const oldValue = changes['showCaptureViewer'].previousValue;
      const newValue = changes['showCaptureViewer'].currentValue;
      if(oldValue !== newValue) {
        if(newValue === true) {
          this.captureViewer?.currentDocument?.deleteAllPages();
          this.captureViewer?.play();
        } else {
          this.captureViewer?.stop()
        }
      }
    }
  }
}

<div id="viewerContainer"
    [style.display]= "showCaptureViewer? '' : 'none'"
></div>
