// samples/0.hello-world/hello-world-vue3/src/App.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import CaptureViewer from './Component/CaptureViewer.vue'
import ImageContainer from './Component/ImageContainer.vue'

const showCaptureViewer = ref(true)
const images = reactive({
  originalImage: '',
  detectedImage: ''
})

const switchVisibility = (value: boolean) => {
  showCaptureViewer.value = value
}
const setImages = (value: { originalImage: string; detectedImage: string }) => {
  const { originalImage, detectedImage } = value
  images.originalImage = originalImage
  images.detectedImage = detectedImage
}
</script>

<template>
  <CaptureViewer
    :showCaptureViewer="showCaptureViewer"
    @switchVisibility="switchVisibility"
    @setImages="setImages"
  ></CaptureViewer>
  <ImageContainer
    :showCaptureViewer="showCaptureViewer"
    :images="images"
    @switchVisibility="switchVisibility"
  ></ImageContainer>
</template>

<style>
html,
body {
  width: 100%;
  height: 100%;
  margin: 0 0;
  padding: 0 0;
}

#app {
  width: 100%;
  height: 100%;
}
</style>

// samples/hello-world/hello-world-react/src/App.js
import './App.css';
import ImageContainer from './components/ImageContainer';
import CaptureViewer from './components/CaptureViewer';
import { useState } from 'react';

function App() {
  const [showCaptureViewer, setShowCaptureViewer] = useState(true);
  const [images, setImages] = useState({
    originalImage: '',
    detectedImage: ''
  });


  return (
    <>
      <CaptureViewer
          showCaptureViewer = { showCaptureViewer }
          setShowCaptureViewer = { setShowCaptureViewer }
          setImages = { setImages }
      /> 
      <ImageContainer
        showCaptureViewer = { showCaptureViewer }
        setShowCaptureViewer = { setShowCaptureViewer }
        images = { images }
      />
    </>
  );
}

export default App;
