// samples/frameworks/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { MobileWebCapture } from 'dynamsoft-mobile-web-capture';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    // Visit https://www.dynamsoft.com/mobile-web-capture/docs/guides/mobile-web-capture-customization.html for more customization options
    // Configuration object for initializing the Mobile Web Capture instance
    const config = {
      license: 'YOUR_LICENSE_KEY_HERE', // Replace with your Dynamsoft license key
      documentScannerConfig: {
        scannerViewConfig: {
          enableAutoCropMode: true, // Enables auto crop and smart capture
        },
      },
    };

    const mobileWebCapture = new MobileWebCapture(config);

    // Launch the capture interface
    mobileWebCapture.launch();
  }
}

<div class="mwc-hello-world-page">
  <div class="mwc-title">
    <h2 class="mwc-title-text">Mobile Web Capture for Angular</h2>
    <img class="mwc-title-logo" src="./favicon.ico" alt="logo" />
  </div>
</div>

// samples/frameworks/react-hooks/src/App.js
import { useEffect } from "react";
import { MobileWebCapture } from "dynamsoft-mobile-web-capture";
import reactLogo from "./logo.svg";
import "./App.css";

function App() {
  useEffect(() => {
    // Visit https://www.dynamsoft.com/mobile-web-capture/docs/guides/mobile-web-capture-customization.html for more customization options
    // Configuration object for initializing the Mobile Web Capture instance
    const config = {
      license: "YOUR_LICENSE_KEY_HERE", // Replace with your Dynamsoft license key
      documentScannerConfig: {
        scannerViewConfig: {
          enableAutoCropMode: true, // Enables auto crop and smart capture
        },
      },
    };

    const mobileWebCapture = new MobileWebCapture(config);

    mobileWebCapture.launch();
  }, []);

  return (
    <div className="mwc-hello-world-page">
      <div className="mwc-title">
        <h2 className="mwc-title-text">Hello World for React</h2>
        <img className="mwc-title-logo" src={reactLogo} alt="logo"></img>
      </div>
    </div>
  );
}

export default App;
